M48
; DRILL file {KiCad 8.0.6} date 2024-11-25T13:49:09+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-25T13:49:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X7.85Y-4.9402
X8.0776Y-4.9402
T2
X2.8228Y-4.9516
X2.8228Y-5.4016
M30
